### ISSUE TITLE
SurfXPiRT Stable Debian 12 does not start after system update

### ISSUE THREAD

**Issue by mirek23** [DAryanMR/SurfXPiRT#1]
I followed all the steps to install debian 12 on Surface RT
All went fine and the system was booting properly from the internal Flash (eMMM)
When I did the system update
sudo apt-get update
sudo apt-get upgrade
The system did not boot.
It keeps trying to start the window manager and the window manager keeps crashing.
I was not able to determine what causes the crash.

**Comment by DAryanMR** [comment]
Does the issue still persist? I noticed it before, but currently the system should boot even after updating.
